sudo: required
language: node_js

node_js:
  - node

env:
  global:
    - AWS_S3_REGION=us-east-2
    - STAGING_BRANCH=develop 
    - SANDBOX_BRANCH=sandbox
    - PRODUCTION_BRANCH=production

install:
  - set -e
  - yarn
  - yarn add create-react-app

script:
  - set -e
  - export NODE_ENV="staging"
  - export CLOUDFRONT_DIST_ID=$CLOUDFRONT_DIST_ID_STAGING
  - |
    if [ $TRAVIS_BRANCH == "$SANDBOX_BRANCH" ]; then
      export NODE_ENV="sandbox"
      export CLOUDFRONT_DIST_ID=$CLOUDFRONT_DIST_ID_SANDBOX
    fi    
  - |
    if [ $TRAVIS_BRANCH == "$PRODUCTION_BRANCH" ]; then
      export NODE_ENV="production"
      export CLOUDFRONT_DIST_ID=$CLOUDFRONT_DIST_ID_PRODUCTION
    fi  
  - echo $NODE_ENV
  - echo $CLOUDFRONT_DIST_ID
  - yarn build

after_success:
  - set -e
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash .travis/deploy.sh; fi'
